export default {
    ADD_NOTE: "ADD_NOTE",
    REMOVE_NOTE: "REMOVE_NOTE",
    CHANGE_TITLE: "CHANGE_TITLE",
    SET_CONTENT: "SET_CONTENT",
    SELECT_NOTE: "SELECT_NOTE",
    SET_TITLE: "SET_TITLE",
    SET_BLOCKED: "SET_BLOCKED"
}
